<a href="https://colab.research.google.com/github/YashSawant5151/Simple_Python_Programs/blob/main/Experiment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### a) Create a 3x3 square matrix and compute its determinant.

In [23]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 Matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")

Original 3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0


### b) Find the inverse of the matrix.

In [24]:
import numpy as np

# Create a 3x3 matrix (using a different one since the previous one has a determinant of 0)
invertible_matrix = np.array([
    [1, 2, 0],
    [0, 1, 0],
    [0, 0, 1]
])

print("Matrix for inverse calculation:")
print(invertible_matrix)

# Check if the determinant is non-zero before attempting inverse
if np.linalg.det(invertible_matrix) != 0:
    inverse_matrix = np.linalg.inv(invertible_matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
else:
    print("\nThis matrix is singular (determinant is zero) and does not have an inverse.")

Matrix for inverse calculation:
[[1 2 0]
 [0 1 0]
 [0 0 1]]

Inverse of the matrix:
[[ 1. -2.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### c) Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20

In [25]:
import numpy as np

# Coefficients matrix (A)
A = np.array([
    [2, 3],
    [4, 5]
])

# Constants matrix (b)
b = np.array([10, 20])

print("Coefficient Matrix (A):")
print(A)
print("\nConstant Vector (b):")
print(b)

# Solve the system of linear equations
x_y = np.linalg.solve(A, b)

print(f"\nSolution (x, y): {x_y}")
print(f"x = {x_y[0]:.2f}")
print(f"y = {x_y[1]:.2f}")

Coefficient Matrix (A):
[[2 3]
 [4 5]]

Constant Vector (b):
[10 20]

Solution (x, y): [5. 0.]
x = 5.00
y = 0.00
